### ISSUE TITLE
Add extra metadata information to UI

### ISSUE THREAD

**Issue by camallen** [zooniverse/PRN-maps#34]
Event layer metadata now contain `description` and `legend` attributes. 
E.g. https://planetary-response-network.s3.amazonaws.com/events/caribbean_2018_demo/layers/pending/v1/metadata.json

The description attribute should be used instead of the layer name in the UI. Also the description and legend (if it exists) should be used on a heatmap point click to describe the point data.

Also there is a top level AOI field that describes the layer region, this could be used in combination with the upload version in the UI.

**Comment by shaunanoordin** [comment]
This Issue has been partially addressed by #37 
- ✔️ _ The description attribute should be used instead of the layer name in the UI._
- ❌  _Also the description and legend (if it exists) should be used on a heatmap point click to describe the point data._

I'm currently having trouble mapping the legends with the actual data in the heatmap, e.g. mapping `["20 to 40% damage", "40 to 80% damage", "above 80% damage"]` to arbitrary values like `2, 3, 5`
